### ISSUE TITLE
Problème de performance - dashboard

### ISSUE THREAD

**Issue by laurentromary** [CCSDForge/episciences#1] opened 2021-01-14 06:46 UTC
Dans l'interface de gestion des article (e.g. [https://jdmdh.episciences.org/administratepaper/list](https://jdmdh.episciences.org/administratepaper/list)), le champ de recherche a un comportement extrêmement lent pour sélectionner les articles concernés au fur et à mesure de la frappe. Cette même interface fonctionne sans problème lorsqu'il s'agit de recherche des utilisations (dans [https://jdmdh.episciences.org/user/list](https://jdmdh.episciences.org/user/list). Y aurait-il moyen d'améliorer cela pour rendre le travail sur les articles plus efficaces? Merci d'avance.

**Comment by a3nm** [comment] 2021-05-21 12:55
Hi Laurent, it seems that some links are missing in your message?

This being said, if the problem is about search being slow when searching for an article in the list of articles, I can definitely reproduce this. E.g., on https://lmcs.episciences.org/administratepaper/list inputting a keyword in the search box takes a very long time to complete. It would be great if this could be optimized.

Thanks a lot for your efforts on developing the platform!

Best regards,

-- 
Antoine Amarilli

**Comment by laurentromary** [comment] 2021-05-21 12:59
Oups. Corrected them :—}. Thanks Antoine.
But yes, this is exactly it. This search box takes ages to provide results.
Laurent

**Comment by a3nm** [comment] 2021-05-21 16:53
I had a look with @charles-paperman. From what seems to be the function doing the querying, https://github.com/CCSDForge/episciences/blob/develop/library/Episciences/PapersManager.php#L449
and from the database schema https://github.com/CCSDForge/episciences/blob/develop/src/mysql/episciences.sql
one way to improve performance here could be to add an index on the database on the table "\`PAPERS\`", namely "FULLTEXT(\`RECORD\`)".

Would that be doable?

**Comment by laurentromary** [comment] 2021-05-21 16:57
@rtournoy qu'est ce que tu en penses?

**Comment by rtournoy** [comment] 2021-05-25 17:09
Hi,
many thanks to @laurentromary @a3nm @charles-paperman for the much appreciated feedback and performance hints.

- I have added a fulltext index
- I have noticed at the same time that other indexes were missing in our production database, that's fixed
- Also the search box was immediately triggering a full search for every character input. Now we wait 2 sec before actually sending a meaningful search. Actually the first character always triggers a rather useless search, we need to wait for at least 2 or 3 characters: this is something that will be fixed soon hopefully. After that we should be able to lower the 2 sec delay to 1 sec.

It seems to have improved the response time, but I'm interested in your feedback. 

thanks!

**Comment by laurentromary** [comment] 2021-05-25 17:18
Clearly improved. You rock, Raphael! Thanks.

**Comment by a3nm** [comment] 2021-05-25 17:29
I confirm that this makes the search much, much faster! Thanks a lot.

I think the user experience could be improved just a small bit by delaying the searches as you proposed. Currently, while you are typing, there are searches that get triggered. As you proposed, I think ideally you would want to start searching when the user has typed some meaningful number and characters AND has not typed for 1 second (say). Further, if a search is ongoing, then once the user starts typing it should invalidate the search (not show briefly the results of an obsolete search).

In terms of interface, I'm not sure if the best would be to show the search animation when a search is actually triggered, or to start showing an animation as soon as the user starts typing, and until a search is completed.

Anyway, that's just a bit of polish, but with the right indexes the search is now much more usable. Thanks a lot, again!

PS: were the indexes added only in production, or will they also show up in https://github.com/CCSDForge/episciences/blob/develop/src/mysql/episciences.sql?

**Comment by rtournoy** [comment] 2021-05-26 09:06
Thank you! I will leave this issue opened for further improvements. I have updated the DB schema:
https://github.com/CCSDForge/episciences/commit/32b5b52e2dd567690d12d832671fcbbf6796efe6

**Closed** 2023-11-27 14:20 UTC
